name: PyPI release

on:
  push:
    branches:
      - master

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build setuptools twine toml

    - name: Build and upload esp-debug-backend ${{ github.event.release.tag_name }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PROJECT_TOKEN }}
      run: |
        PUBLISHED_VERSION=$(curl https://pypi.org/pypi/esp-debug-backend/json 2>/dev/null | jq -r '.info.version')
        CURRENT_VERSION=$(python -c "import toml;print(toml.load('pyproject.toml')['project']['version'])" 2>/dev/null)
        if [ "$PUBLISHED_VERSION" == "$CURRENT_VERSION" ]; then
          echo "Version ${PUBLISHED_VERSION} already published, skipping..."
          exit 0
        else
          echo "Packaging and publishing new esp-debug-backend version: ${CURRENT_VERSION}"
          python -m build
          twine check dist/* && twine upload dist/*
        fi
